# Generated by Django 5.0.2 on 2024-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_person_remove_book_author_delete_author_delete_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the project title", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter the project description"),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
