# Generated by Django 5.0.2 on 2024-10-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_academicproject_delete_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicproject",
            name="date_posted",
        ),
        migrations.AlterField(
            model_name="academicproject",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="academicproject",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
