# Generated by Django 5.0.2 on 2024-10-15 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
