# Generated by Django 5.0.2 on 2024-10-19 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
